# permissions for end users to edit ibmobjectcsis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ibmobjectcsi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-object-csi-driver-operator
  name: ibmobjectcsi-editor-role
rules:
- apiGroups:
  - objectdriver.csi.ibm.com
  resources:
  - ibmobjectcsis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectdriver.csi.ibm.com
  resources:
  - ibmobjectcsis/status
  verbs:
  - get
