# permissions for end users to view recoverstalevolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recoverstalevolume-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-object-csi-driver-operator
    app.kubernetes.io/part-of: ibm-object-csi-driver-operator
    app.kubernetes.io/managed-by: kustomize
  name: recoverstalevolume-viewer-role
rules:
- apiGroups:
  - objectdriver.csi.ibm.com
  resources:
  - recoverstalevolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - objectdriver.csi.ibm.com
  resources:
  - recoverstalevolumes/status
  verbs:
  - get
