# permissions for end users to edit restorestalevolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: restorestalevolume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-object-csi-driver-operator
    app.kubernetes.io/part-of: ibm-object-csi-driver-operator
    app.kubernetes.io/managed-by: kustomize
  name: restorestalevolume-editor-role
rules:
- apiGroups:
  - objectdriver.csi.ibm.com
  resources:
  - restorestalevolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectdriver.csi.ibm.com
  resources:
  - restorestalevolumes/status
  verbs:
  - get
