apiVersion: objectdriver.csi.ibm.com/v1alpha1
kind: IBMObjectCSI
metadata:
  name: ibm-object-csi
  namespace: ibm-object-csi-operator
  labels:
    app.kubernetes.io/name: ibm-object-csi
    app.kubernetes.io/instance: ibm-object-csi
    app.kubernetes.io/part-of: ibm-object-csi-driver
    app.kubernetes.io/managed-by: ibm-object-csi-driver-operator
    release: v1.0.6
spec:
  # controller is a deployment with ibm-object-csi-controller container
  # and csi-provisioner and livenessprobe sidecars.
  controller:
    repository: icr.io/ibm/ibm-object-csi-driver
    tag: "v1.0.6"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 800m
        memory: 400Mi
      requests:
        cpu: 40m
        memory: 40Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - controller
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

  # node is a daemonSet with ibm-object-csi-node container
  # and csi-node-driver-registrar and livenessprobe sidecars.
  node:
    repository: icr.io/ibm/ibm-object-csi-driver
    tag: "v1.0.6"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 120m
        memory: 300Mi
      requests:
        cpu: 30m
        memory: 75Mi

  sidecars:
  - name: csi-node-driver-registrar
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: "v2.13.0"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 40m
        memory: 80Mi
      requests:
        cpu: 10m
        memory: 20Mi
  - name: csi-provisioner
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: "v5.2.0"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 80m
        memory: 160Mi
      requests:
        cpu: 20m
        memory: 40Mi
  - name: livenessprobe
    repository: k8s.gcr.io/sig-storage/livenessprobe
    tag: "v2.15.0"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 10Mi
