apiVersion: objectdriver.csi.ibm.com/v1alpha1
kind: RecoverStaleVolume
metadata:
  labels:
    app.kubernetes.io/name: recoverstalevolume
    app.kubernetes.io/instance: recoverstalevolume-sample
    app.kubernetes.io/part-of: ibm-object-csi-driver
    app.kubernetes.io/managed-by: ibm-object-csi-driver-operator
  name: recoverstalevolume-sample
  namespace: ibm-object-csi-operator
spec:
  logHistory: 200
  data:
    - namespace: default
      deployments: []