## Append samples you want in your CSV to this file as resources ##
resources:
- csi_v1alpha1_ibmobjectcsi.yaml
- csi_v1alpha1_recoverstalevolume.yaml
labels:
  - app.kubernetes.io/part-of: ibm-object-csi-driver-operator
  - app.kubernetes.io/managed-by: kustomize
#+kubebuilder:scaffold:manifestskustomizesamples
