// Package v1alpha1 ...
package v1alpha1

// DriverPhase ...
type DriverPhase string

const (
	// DriverPhaseNone ...
	DriverPhaseNone DriverPhase = ""
	// DriverPhaseCreating ...
	DriverPhaseCreating DriverPhase = "Creating"
	// DriverPhaseRunning ...
	DriverPhaseRunning DriverPhase = "Running"
	// DriverPhaseFailed ...
	DriverPhaseFailed DriverPhase = "Failed"
)
