resources:
- bases/config.yaml
patchesJson6902:
- path: patches/basic.config.yaml
  target:
    group: scorecard.operatorframework.io
    version: v1alpha3
    kind: Configuration
    name: config
- path: patches/olm.config.yaml
  target:
    group: scorecard.operatorframework.io
    version: v1alpha3
    kind: Configuration
    name: config
commonLabels:
  app.kubernetes.io/part-of: ibm-object-csi-driver
  app.kubernetes.io/managed-by: ibm-object-csi-driver-operator
#+kubebuilder:scaffold:patchesJson6902
